#pragma once

#include <string>
#include <vector>

#include "core/core.h"

namespace abyss::rules {

// How a rule's present condition groups combine. A "group" is one of:
// filenameEquals, filenameContains, containsAll, containsAny, containsNone
// (negation), sha256Hashes — see README.md. Groups the rule
// doesn't configure at all are simply absent and never considered.
enum class RuleLogic {
    Any,  // fires if at least one present group matches (default; historical behavior)
    All,  // fires only if every present group matches
    NOf,  // fires if at least `nOfThreshold` present groups match
};

// A loaded rule. IOC/hash rules match known literal signatures (strings,
// hashes, known filenames). STRUCTURAL/BEHAVIOR/CORRELATION rule *types*
// also exist in the rule pack format for documentation and future engines
// (see README.md), but only literal/hash matching is evaluated by
// RuleEngine in this milestone — semantic structural/behavioral analysis
// (magic-byte mismatch, entropy, concealment, exec-sink combinations) is
// native code in src/scanner, parameterized by rules/core/*.rules thresholds
// rather than by this matcher. True feature-based numeric/time-window/
// ordered-sequence CORRELATION evaluation requires the runtime/ETW
// milestone (there is no timestamped event stream to correlate yet) — see
// README.md.
struct Rule {
    std::string id;
    std::string name;
    int version = 1;
    RuleType type = RuleType::Ioc;
    Severity severity = Severity::Medium;
    Confidence confidence = Confidence::Medium;
    std::string description;
    std::vector<std::string> tags;
    std::string campaign;

    std::vector<std::string> containsAll;   // every substring must be present (AND)
    std::vector<std::string> containsAny;   // at least one substring must be present (OR)
    std::vector<std::string> containsNone;  // NONE of these substrings may be present (negation)
    std::vector<std::string> sha256Hashes;  // lowercase hex; file's SHA-256 must equal one of these
    std::vector<std::string> filenameEquals;   // case-insensitive exact basename match
    std::vector<std::string> filenameContains; // case-insensitive basename substring match
    std::vector<std::string> appliesToExtensions; // empty => applies to all extensions

    RuleLogic logic = RuleLogic::Any;
    int nOfThreshold = 1; // only meaningful when logic == NOf

    bool sourceFileValid = true;
    std::string sourceFile;
};

struct RuleLoadResult {
    std::vector<Rule> rules;
    std::vector<std::string> errors; // non-fatal: per-file parse errors, collected not thrown
};

// Loads a single `.rules` file (block format, see README.md).
RuleLoadResult loadRulesFromFile(const std::string& path);

// Recursively loads every `.rules` file under a directory.
RuleLoadResult loadRulesFromDirectory(const std::string& dir);

// Scans a rule set (typically the concatenation of several
// loadRulesFromDirectory() calls) for duplicate `id` values and returns one
// diagnostic string per duplicate found (empty if none). A duplicate ID is
// treated as a poisoned/ambiguous rule pack — see README.md.
std::vector<std::string> findDuplicateRuleIds(const std::vector<Rule>& rules);

class RuleEngine {
public:
    explicit RuleEngine(std::vector<Rule> rules) : rules_(std::move(rules)) {}

    const std::vector<Rule>& rules() const { return rules_; }

    // Evaluates all loaded rules against one file's content + name.
    // `content` should be the file's text content (lossy-decoded for binary
    // files is fine — IOC substrings are matched byte-for-byte in practice).
    // `sha256Lower` is the file's lowercase-hex SHA-256, or empty if hashing
    // was skipped (ScanOptions::computeHashes=false) — rules with a
    // sha256Hashes condition simply cannot match when it's empty.
    std::vector<Finding> evaluateFile(const std::string& relPath, const std::string& filename,
                                       const std::string& extensionLower, const std::string& content,
                                       const std::string& sha256Lower = {}) const;

private:
    std::vector<Rule> rules_;
};

// ---------------------------------------------------------------------------
// Rule pack integrity — a plain SHA-256 hash manifest (`MANIFEST.sha256`,
// one `<64-hex-sha256>  <relative-path>` line per shipped .rules/.esr file,
// same two-space format as `sha256sum`). This is NOT Authenticode/code-
// signing — Abyss v0.1 has no certificate/signing pipeline — it only
// detects post-install tampering of the rule pack shipped alongside a
// given build, generated by tools/generate_rules_manifest.ps1 at release
// time. See README.md "Trusted rule boundary" and
// README.md for the honest scope of this guarantee.
// ---------------------------------------------------------------------------

struct ManifestVerification {
    bool manifestFound = false;
    bool manifestReadable = false;
    bool anchorAvailable = false; // a compiled-in trust anchor exists to check the manifest itself against
    bool anchorVerified = false;  // the manifest file's own hash matched the compiled-in anchor
    // true iff: manifest found+readable, anchor verified (when one is compiled in), every listed file's
    // hash matches, no manifest entry was rejected for an unsafe/duplicate path, and nothing on disk is
    // untracked.
    bool allVerified = false;
    std::vector<std::string> mismatches;     // "<relpath>: <reason>" -- hash mismatch / missing file
    std::vector<std::string> untracked;      // .rules/.esr files on disk but absent from the manifest
    std::vector<std::string> rejectedPaths;  // manifest lines rejected: absolute, '..', symlink escape, duplicate
    std::vector<std::string> errors;         // iterator/file-read errors encountered while verifying
};

// Verifies rules/MANIFEST.sha256 against the files actually present under
// `rulesDir`. Every manifest-listed relative path is canonicalized and must
// resolve to a location inside `rulesDir` — absolute paths, `..` traversal,
// and symlink/junction escapes are rejected outright (into `rejectedPaths`,
// which also counts against allVerified) rather than silently followed.
// Also checks the manifest FILE's own hash against a trust anchor compiled
// into this binary (see src/rules/trust_anchor.h) when one is available —
// this is what stops an attacker who copies abyss.exe next to their own
// self-consistent rules+manifest pair from being treated as "official": the
// anchor is independent of anything shipped beside the binary. See
// README.md "Trusted rule boundary".
ManifestVerification verifyRuleManifest(const std::string& rulesDir);

} // namespace abyss::rules
