#pragma once

// GENERATED FILE -- do not hand-edit. Regenerated by
// tools/generate_rules_manifest.ps1 alongside rules/MANIFEST.sha256, and
// must be checked in and rebuilt together with any change under rules/.
//
// kOfficialManifestSha256 is the SHA-256 of the exact bytes of
// rules/MANIFEST.sha256 at the time this header was generated, baked into
// the compiled binary. rules::verifyRuleManifest() compares the manifest
// file's own hash against this constant before trusting anything the
// manifest itself claims -- a manifest is otherwise just a file sitting next
// to the rules it describes, and an attacker who can write both can trivially
// keep them self-consistent. Binding the expected manifest hash into the
// binary itself is what makes that self-consistency insufficient on its
// own. See README.md 'Trusted rule boundary' and
// README.md for what this does and does not guarantee (it is a
// build-time hash anchor, not Authenticode/code-signing).
//
// An empty string means no anchor has been generated -- verifyRuleManifest()
// then treats the pack as untrustable (INCOMPLETE), never a silent pass.

namespace abyss::rules {

inline constexpr const char* kOfficialManifestSha256 = "b67c2c89f6245824eb0d0cef797d975d49927ba6f1a19167e2ad8adc80486259";

} // namespace abyss::rules
