# Regenerates rules/MANIFEST.sha256 (the integrity manifest Abyss checks at
# load time) AND src/rules/trust_anchor.h (the compiled-in trust anchor
# that binds the manifest itself to the binary -- see README.md,
# "Trusted rule boundary"). These two files must always be regenerated
# together: the anchor is the SHA-256 of the manifest file's own bytes, so
# a stale anchor after a rules/ change makes every subsequent official-
# trust scan report "tampered" until this script is re-run and the binary
# is rebuilt.
#
# This is a maintainer/release-time tool, not a runtime dependency of
# Abyss itself: it uses only PowerShell's built-in Get-FileHash (no
# third-party package), the same constraint the core C++ product follows.
# Run this after any change under rules/, then rebuild abyss.exe, then
# commit both regenerated files.

param(
    [string]$RulesDir = (Join-Path $PSScriptRoot "..\rules"),
    [string]$AnchorHeaderPath = (Join-Path $PSScriptRoot "..\src\rules\trust_anchor.h")
)

$RulesDir = (Resolve-Path $RulesDir).Path
$manifestPath = Join-Path $RulesDir "MANIFEST.sha256"

$files = Get-ChildItem -Path $RulesDir -Recurse -File | Where-Object {
    $_.Extension -eq ".rules" -or $_.Extension -eq ".esr"
} | Sort-Object FullName

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Abyss rule pack integrity manifest - generated by tools/generate_rules_manifest.ps1")
$lines.Add("# Format: sha256-hex, two spaces, path relative to rules/ (forward slashes).")
$lines.Add("# Regenerate after any change under rules/ and commit the result.")

foreach ($f in $files) {
    $hash = (Get-FileHash -Path $f.FullName -Algorithm SHA256).Hash.ToLower()
    $rel = $f.FullName.Substring($RulesDir.Length + 1) -replace '\\', '/'
    $lines.Add("$hash  $rel")
}

Set-Content -Path $manifestPath -Value $lines -Encoding ascii
Write-Output ("Wrote {0} entries to {1}" -f $files.Count, $manifestPath)

# Trust anchor: SHA-256 of the manifest file's own bytes (the exact bytes
# just written above), baked into the compiled binary.
$manifestHash = (Get-FileHash -Path $manifestPath -Algorithm SHA256).Hash.ToLower()

$anchorLines = New-Object System.Collections.Generic.List[string]
$anchorLines.Add("#pragma once")
$anchorLines.Add("")
$anchorLines.Add("// GENERATED FILE -- do not hand-edit. Regenerated by")
$anchorLines.Add("// tools/generate_rules_manifest.ps1 alongside rules/MANIFEST.sha256, and")
$anchorLines.Add("// must be checked in and rebuilt together with any change under rules/.")
$anchorLines.Add("//")
$anchorLines.Add("// kOfficialManifestSha256 is the SHA-256 of the exact bytes of")
$anchorLines.Add("// rules/MANIFEST.sha256 at the time this header was generated, baked into")
$anchorLines.Add("// the compiled binary. rules::verifyRuleManifest() compares the manifest")
$anchorLines.Add("// file's own hash against this constant before trusting anything the")
$anchorLines.Add("// manifest itself claims -- a manifest is otherwise just a file sitting next")
$anchorLines.Add("// to the rules it describes, and an attacker who can write both can trivially")
$anchorLines.Add("// keep them self-consistent. Binding the expected manifest hash into the")
$anchorLines.Add("// binary itself is what makes that self-consistency insufficient on its")
$anchorLines.Add("// own. See README.md 'Trusted rule boundary' and")
$anchorLines.Add("// README.md for what this does and does not guarantee (it is a")
$anchorLines.Add("// build-time hash anchor, not Authenticode/code-signing).")
$anchorLines.Add("//")
$anchorLines.Add("// An empty string means no anchor has been generated -- verifyRuleManifest()")
$anchorLines.Add("// then treats the pack as untrustable (INCOMPLETE), never a silent pass.")
$anchorLines.Add("")
$anchorLines.Add("namespace abyss::rules {")
$anchorLines.Add("")
$anchorLines.Add("inline constexpr const char* kOfficialManifestSha256 = ""$manifestHash"";")
$anchorLines.Add("")
$anchorLines.Add("} // namespace abyss::rules")

Set-Content -Path $AnchorHeaderPath -Value $anchorLines -Encoding ascii
Write-Output ("Wrote trust anchor ($manifestHash) to $AnchorHeaderPath")
Write-Output "IMPORTANT: rebuild abyss.exe now so the new anchor is compiled in."
